import re
import os
import glob
import pandas as pd
import subprocess as sp

configfile: "config/config.yaml"

# Load sample data 
df = pd.read_table('config/sample_sheet.csv', sep=',').set_index('sample_name', drop=False)
print(df)

wildcard_constraints:
    bioproject="\w+",
    accession="\w+",
    read="(_1|_2)?"
#    sample="|".join(df.index)

# Function to check if a sample is coming from SRA
def check_sample(accession, bioproject):
    pattern = r"^(SRR|ERR|DRR)[0-9]+$"
    if re.match(pattern, accession):
        return f"samples/{bioproject}/{accession}/{accession}.sra"

# List of SRA sample paths
sra_samples = [
    check_sample(row['run'], row['bioproject'])
    for _, row in df.iterrows()
    if check_sample(row['run'], row['bioproject']) is not None
]

def get_local_sample(accession, bioproject):
    pattern = r"^(SRR|ERR|DRR)[0-9]+$"
    if not re.match(pattern, accession):
        sample_dir = f"samples/{bioproject}/{accession}"
        if os.path.exists(sample_dir):
        # Check for paired-end files
            paired_files = sorted(glob.glob(f"{sample_dir}/{accession}_[1-2].fastq.gz"))
            if len(paired_files) == 2:
                return ('pe', paired_files)
            
            # Check for single-end file
            single_file = glob.glob(f"{sample_dir}/{accession}.fastq.gz")
            if single_file:
                return ('se', single_file[0])

            # If no matching files found, return None
            return None
    return None

# Initialize separate lists for paired-end and single-end samples
local_samples_pe = []
local_samples_se = []

for _, row in df.iterrows():
    result = get_local_sample(row['run'], row['bioproject'])
    if result is not None:
        sample_type, sample_files = result
        if sample_type == 'pe':
            local_samples_pe.extend(sample_files)  # Add both files for paired-end
        else:
            local_samples_se.append(sample_files)  # Add single file for single-end

## Print the results
#print("Paired-end local samples found:")
#for sample in local_samples_pe:
#    print(sample)

#print("Single-end local samples found:")
#for sample in local_samples_se:
#    print(sample)


#Global lists for output files
all_output_pe = [] + local_samples_pe
all_output_se = [] + local_samples_se


for sra_file in sra_samples:

    # Function to check if a sample is paired-end
    def isPairedSRA(sra_file):
        sra_file = os.path.abspath(sra_file)
        if not os.path.exists(sra_file):
            print(f"File {sra_file} does not exist. Skipping paired-end check.")
            return None  # Return None or handle as needed
        try:
            contents = sp.check_output(["fastq-dump", "-X", "1", "-Z", "--split-spot", sra_file], text=True)
        except sp.CalledProcessError as e:
            raise Exception(f"Error running fastq-dump on {sra_file}: {e}")
    
        if contents.count("\n") == 4:
            return False
        elif contents.count("\n") == 8:
            return True
        else:
            print(f"Unexpected output from fastq-dump on {sra_file}")
            return None  # Handle unexpected output


    # Function to generate expected output files based on paired-end status
    def get_output_files(wildcards):
        sra_file = f"samples/{wildcards['bioproject']}/{wildcards['accession']}/{wildcards['accession']}.sra"
        if isPairedSRA(sra_file):
            return [
                f"samples/{wildcards['bioproject']}/{wildcards['accession']}/{wildcards['accession']}_1.fastq.gz",
                f"samples/{wildcards['bioproject']}/{wildcards['accession']}/{wildcards['accession']}_2.fastq.gz"
            ]
        else:
            return [
                f"samples/{wildcards['bioproject']}/{wildcards['accession']}/{wildcards['accession']}.fastq.gz"
            ]
        

# Populate the output lists based on paired-end status
for sra_file in sra_samples:
    # Extract bioproject and accession from the file path
    parts = sra_file.split('/')
    wildcards = {'bioproject': parts[1], 'accession': parts[2]}
    output_files = get_output_files(wildcards)
    if isPairedSRA(sra_file):
        all_output_pe.extend(output_files)
    else:
        all_output_se.extend(output_files)

#print("Paired-end outputs:", all_output_pe)
#print("Single-end outputs:", all_output_se)

#for file in all_output_pe:
#    print(file)
#for file in all_output_se:
#    print(file)

fastqc_output_pe = []
fastqc_output_se = []
trimmed_output_pe = []
trimmed_output_se = []

for file in all_output_pe:
    basefqcpre = file.replace("samples/", "results/qc/fastqc_pre/").replace(".fastq.gz", "")
    fastqc_output_pe.extend([f"{basefqcpre}_fastqc.html", f"{basefqcpre}_fastqc.zip"])
    basetrm = file.replace("samples/", "results/trimmed/").replace(".fastq.gz", "")
    trimmed_output_pe.extend([f"{basetrm}_trimmed.fastq.gz"])
    basefqcaft = file.replace("samples/", "results/qc/fastqc_aft/").replace(".fastq.gz", "")
    fastqc_output_pe.extend([f"{basefqcaft}_trimmed_fastqc.html", f"{basefqcaft}_trimmed_fastqc.zip"])

for file in all_output_se:
    basefqcpre = file.replace("samples/", "results/qc/fastqc_pre/").replace(".fastq.gz", "")
    fastqc_output_se.extend([f"{basefqcpre}_fastqc.html", f"{basefqcpre}_fastqc.zip"])
    basetrm = file.replace("samples/", "results/trimmed/").replace(".fastq.gz", "")
    trimmed_output_se.extend([f"{basetrm}_trimmed.fastq.gz"])
    basefqcaft = file.replace("samples/", "results/qc/fastqc_aft/").replace(".fastq.gz", "")
    fastqc_output_pe.extend([f"{basefqcaft}_trimmed_fastqc.html", f"{basefqcaft}_trimmed_fastqc.zip"])

fastqc_pre_output = fastqc_output_pe + fastqc_output_se
#for file in fastqc_pre_output:
#    print(file)
trimmed_output = trimmed_output_pe + trimmed_output_se
#for file in trimmed_output:
#    print(file)

def get_gtf_files(wildcards):
    gtf_files = expand("results/assembly/{bioproject}/{accession}.gtf",
                       bioproject=wildcards.bioproject,
                       accession=df[df['bioproject'] == wildcards.bioproject]['run'])
 #   print(f"GTF files for bioproject {wildcards.bioproject}:")
 #   print(gtf_files)
    return gtf_files


rule all:
    input:
#        sra_samples,
        all_output_pe,
        all_output_se,
        local_samples_pe,
        local_samples_se,
        fastqc_output_pe,
        fastqc_output_se,
        trimmed_output_pe,
        trimmed_output_se,
        "genome/hisat2_index/genome.1.ht2",
        expand("results/sorted/{bioproject}/{accession}_sorted.bam", zip, bioproject=df.bioproject, accession=df.run),
        expand("results/assembly/{bioproject}/{bioproject}_stringtie_merged.gtf", bioproject=df.bioproject),
        expand("results/assembly/{bioproject}/{bioproject}_sample_lst.txt", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/phenodata.csv", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/gene_count_matrix.csv", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/parameters.txt", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/Enhanced_Volcano_Plot.png", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/Improved_PCA_Plot.png", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/Top50_DEGs_Heatmap.png", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/KEGG_enrichment.csv", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/GO_enrichment.csv", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/KEGG_dotplot.png", bioproject=df.bioproject),
        expand("results/deg/{bioproject}/GO_dotplot.png", bioproject=df.bioproject)


rule fasterq_dump_pe:
    input:
        "samples/{bioproject}/{accession}/{accession}.sra"
    output:
        "samples/{bioproject}/{accession}/{accession}_1.fastq",
        "samples/{bioproject}/{accession}/{accession}_2.fastq"
##    threads: config['THREADS']['zhex']
##    resources:
##        mem_mb=config['RESOURCEMOD']['boost'],
    shell:
        """
        fasterq-dump --split-files samples/{wildcards.bioproject}/{wildcards.accession} \
        -O samples/{wildcards.bioproject}/{wildcards.accession}/
        """
##        """
##        module load autoload profile/bioinf
##        module load autoload sra
##        fasterq-dump --split-files samples/{wildcards.bioproject}/{wildcards.accession} \
##        -O samples/{wildcards.bioproject}/{wildcards.accession}/
##        """

rule fasterq_dump_se:
    input:
        "samples/{bioproject}/{accession}/{accession}.sra"
    output:
        "samples/{bioproject}/{accession}/{accession}.fastq"
##    threads: config['THREADS']['zhex']
##    resources:
##        mem_mb=config['RESOURCEMOD']['boost'],
    shell:
        """
        fasterq-dump samples/{wildcards.bioproject}/{wildcards.accession} \
        -O samples/{wildcards.bioproject}/{wildcards.accession}/
        """
##        """
##        module load autoload profile/bioinf
##        module load autoload sra
##        fasterq-dump samples/{wildcards.bioproject}/{wildcards.accession} \
##        -O samples/{wildcards.bioproject}/{wildcards.accession}/
##        """

ruleorder: fqzip_pe > fqzip_se

# Rule to gzip paired-end FASTQ files
rule fqzip_pe:
    input:
        i1 = "samples/{bioproject}/{accession}/{accession}_1.fastq",
        i2 = "samples/{bioproject}/{accession}/{accession}_2.fastq"
    output:
        o1 = "samples/{bioproject}/{accession}/{accession}_1.fastq.gz",
        o2 = "samples/{bioproject}/{accession}/{accession}_2.fastq.gz"
##    threads: config['THREADS']['fqzip']
##    resources:
##        mem_mb=config['RESOURCEMOD']['boost'],
    shell:
        """
        gzip -c {input.i1} > {output.o1}
        gzip -c {input.i2} > {output.o2}
        """

# Rule to gzip single-end FASTQ files
rule fqzip_se:
    input:
        "samples/{bioproject}/{accession}/{accession}.fastq"
    output:
        "samples/{bioproject}/{accession}/{accession}.fastq.gz"
##    threads: config['THREADS']['fqzip']
##    resources:
##        mem_mb=config['RESOURCEMOD']['boost'],
    shell:
        """
        gzip -c {input} > {output}
        """

# Initial fastqc analysis
rule fastqc_pre:
    input:
        "samples/{bioproject}/{accession}/{accession}{read}.fastq.gz"
    output:
        html="results/qc/fastqc_pre/{bioproject}/{accession}/{accession}{read}_fastqc.html",
        zip="results/qc/fastqc_pre/{bioproject}/{accession}/{accession}{read}_fastqc.zip" # the suffix _fastqc.zip is necessary for multiqc to find the file. If not using multiqc, you are free to choose an arbitrary filename
    log:
        "logs/fastqc_pre/{bioproject}/{accession}{read}.log"
##    params: "--quiet"
##    threads: 1
##    resources:
##        mem_mb=10000,
    shell:
        """
        fastqc -o results/qc/fastqc_pre/{wildcards.bioproject}/{wildcards.accession} -f fastq --extract {input} > {log} 2>&1
        """
##        """
##        module load autoload profile/bioinf
##        module load autoload fastqc
##        fastqc -o results/qc/fastqc_pre/{wildcards.bioproject}/{wildcards.accession} -t {threads} -f fastq --extract {input} > {log} 2>&1
##        module purge
##        """

ruleorder: trimmomatic_pe > trimmomatic_se

rule trimmomatic_pe:
    input:
        r1="samples/{bioproject}/{accession}/{accession}_1.fastq.gz",
        r2="samples/{bioproject}/{accession}/{accession}_2.fastq.gz"
    output:
        r1="results/trimmed/{bioproject}/{accession}/{accession}_1_trimmed.fastq.gz",
        r2="results/trimmed/{bioproject}/{accession}/{accession}_2_trimmed.fastq.gz",
        r1_unpaired="results/trimmed/{bioproject}/{accession}/{accession}_1.unpaired.fastq.gz",
        r2_unpaired="results/trimmed/{bioproject}/{accession}/{accession}_2.unpaired.fastq.gz"
    log:
        "logs/trimmomatic/{bioproject}/{accession}_pe.log"
    params:
        trimmer = ["ILLUMINACLIP:TruSeq3-PE.fa:2:30:10", "LEADING:3", "TRAILING:3", "SLIDINGWINDOW:4:15", "MINLEN:36"]
##        **config["params"]["trimmomatic"]["pe"],
##    threads: config['THREADS']['trimmo']
    shell:
        """
        trimmomatic PE -threads {threads} \
        {input.r1} {input.r2} \
        {output.r1} {output.r1_unpaired} \
        {output.r2} {output.r2_unpaired} \
        {params.trimmer} \
        2> {log}
        """

rule trimmomatic_se:
    input:
        "samples/{bioproject}/{accession}/{accession}.fastq.gz"
    output:
        "results/trimmed/{bioproject}/{accession}/{accession}_trimmed.fastq.gz"
    log:
        "logs/trimmomatic/{bioproject}/{accession}_se.log"
    params:
        trimmer = ["ILLUMINACLIP:TruSeq3-SE.fa:2:30:10", "LEADING:3", "TRAILING:3", "SLIDINGWINDOW:4:15", "MINLEN:36"]
##    **config["params"]["trimmomatic"]["pe"],
##    threads: config['THREADS']['trimmo']
    shell:
        """
        trimmomatic SE -threads {threads} \
        {input} \
        {output} \
        {params.trimmer} \
        2> {log}
        """

# Post trimming fastqc analysis
rule fastqc_aft:
    input:
        "results/trimmed/{bioproject}/{accession}/{accession}{read}_trimmed.fastq.gz"
    output:
        html="results/qc/fastqc_aft/{bioproject}/{accession}/{accession}{read}_trimmed_fastqc.html",
        zip="results/qc/fastqc_aft/{bioproject}/{accession}/{accession}{read}_trimmed_fastqc.zip" # the suffix _fastqc.zip is necessary for multiqc to find the file. If not using multiqc, you are free to choose an arbitrary filename
    log:
        "logs/fastqc_aft/{bioproject}/{accession}{read}_trimmed.log"
##    params: "--quiet"
##    threads: 1
##    resources:
##        mem_mb=10000,
    shell:
        """
        fastqc -o results/qc/fastqc_aft/{wildcards.bioproject}/{wildcards.accession} -f fastq --extract {input} > {log} 2>&1
        """
##        """
##        module load autoload profile/bioinf
##        module load autoload fastqc
##        fastqc -o results/qc/fastqc_pre/{wildcards.bioproject}/{wildcards.accession} -t {threads} -f fastq --extract {input} > {log} 2>&1
##        module purge
##        """

rule hisat2_index:
    input:
        fasta = config["reference_genome"]
    output:
        folder = directory("genome/hisat2_index"),
        index = "genome/hisat2_index/genome.1.ht2"
    log:
        "logs/hisat2_index/index.log"
##    params:
##        prefix = "index_{genome}/"
    threads: 4
##    resources:
##        mem_mb=config['RESOURCEMOD']['high'],
    shell:
        """
        mkdir -p {output.folder}
        hisat2-build -p {threads} {input.fasta} {output.folder}/genome
        """

rule hisat2_align:
    input:
        index = "genome/hisat2_index/genome.1.ht2",
        reads = lambda wildcards: (
            [f"results/trimmed/{wildcards.bioproject}/{wildcards.accession}/{wildcards.accession}_{read}_trimmed.fastq.gz" for read in [1, 2]]
            if f"results/trimmed/{wildcards.bioproject}/{wildcards.accession}/{wildcards.accession}_1_trimmed.fastq.gz" in trimmed_output_pe
            else f"results/trimmed/{wildcards.bioproject}/{wildcards.accession}/{wildcards.accession}_trimmed.fastq.gz"
        )
    output:
        bam = "results/aligned/{bioproject}/{accession}.bam"
    log:
        "logs/hisat2/{bioproject}/{accession}.log"
    threads: 8
    params:
        idx="genome/hisat2_index/genome"
##    resources:
##        mem_mb=config['RESOURCEMOD']['high'],
##        time=config['RESOURCEMOD']['moretime'],
#    run:
#        if isinstance(input.reads, list):
            #Paired-end
#            shell("""
#                hisat2 -x {params.idx} -1 {input.reads[0]} -2 {input.reads[1]} -p {threads} | \
#                samtools view -bS - > {output.bam}
#            """)
#        else:
#            shell("""
#                hisat2 -x {params.idx} -U {input.reads} -p {threads} | \
#                samtools view -bS - > {output.bam}
#            """)
    shell:
        """
        if [ -f {input.reads[1]} ]; then
            hisat2 -x {params.idx} -1 {input.reads[0]} -2 {input.reads[1]} -p {threads} |
            samtools view -bS - > {output.bam}
        else
            hisat2 -x {params.idx} -U {input.reads} -p {threads} |
            samtools view -bS - > {output.bam}
        fi 2> {log}
        """

rule samtools_sort:
    input:
        "results/aligned/{bioproject}/{accession}.bam"
    output:
        "results/sorted/{bioproject}/{accession}_sorted.bam"
##    threads: config['THREADS']['samsort']
##    resources:
##        mem_mb=config['RESOURCEMOD']['high'],
    shell:
        """
        samtools sort {input} -o {output}
        """

rule stringtie:
    input:
        bam = "results/sorted/{bioproject}/{accession}_sorted.bam",
        annotation = config["reference_annotation"]
    output:
        "results/assembly/{bioproject}/{accession}.gtf"
    threads: 4
    shell:
        """
        stringtie {input.bam} \
        -G {input.annotation} \
        -o {output} \
        -e
        """
##        """
##        module load autoload profile/bioinf && \
##        module load stringtie && \
##        module load illumina_genome_Homo_sapiens/hg38 && \
##        stringtie {input} \
##        -G $ANNOTATION/Genes/genes.gtf \
##        -o {output} \
##        -e
##        """

rule merge:
    input:
        gtfs = get_gtf_files,
        annotation = config["reference_annotation"]
    output:
        "results/assembly/{bioproject}/{bioproject}_stringtie_merged.gtf"
    log:
        "logs/assembly/{bioproject}/{bioproject}_stringtie_merged.log"
    threads: 4
    shell:
        """
        stringtie --merge \
        -G {input.annotation} \
        -o {output} \
        {input.gtfs}
        """
##        """
##        module load autoload profile/bioinf && \
##        module load stringtie && \
##        module load illumina_genome_Homo_sapiens/hg38 && \
##        stringtie --merge \
##        -G $ANNOTATION/Genes/genes.gtf \
##        -o {output} \
##        {input}
##        """

rule preprep:
    input:
        i1 = "config/sample_sheet.csv",
        i2 = "results/assembly/{bioproject}/{bioproject}_stringtie_merged.gtf"
    output:
        o1 = "results/assembly/{bioproject}/{bioproject}_sample_lst.txt",
        o2 = "results/deg/{bioproject}/phenodata.csv"
    shell:
        """
        python3 workflow/scripts/preprep.py {input.i1} {input.i2} {output.o1} {output.o2}
        """
# Maybe here should be added a rule to merge the different bioproject files in user-selected groups of samples 

rule prepDE:
    input:
        i1 = "results/assembly/{bioproject}/{bioproject}_sample_lst.txt"
    output:
        o1 = "results/deg/{bioproject}/gene_count_matrix.csv",
        o2 = "results/deg/{bioproject}/transcript_count_matrix.csv"
    shell:
        """
        python3 workflow/scripts/prepDE.py \
        -i {input.i1} -g {output.o1} -t {output.o2}
        """

rule DESeq2:
    input:
        i1 = "results/deg/{bioproject}/phenodata.csv",
        i2 = "results/deg/{bioproject}/gene_count_matrix.csv",
    output:
        "results/deg/{bioproject}/parameters.txt",
        "results/deg/{bioproject}/Enhanced_Volcano_Plot.png",
        "results/deg/{bioproject}/Improved_PCA_Plot.png",
        "results/deg/{bioproject}/Top50_DEGs_Heatmap.png",
        "results/deg/{bioproject}/KEGG_enrichment.csv",
        "results/deg/{bioproject}/GO_enrichment.csv",
        "results/deg/{bioproject}/KEGG_dotplot.png",
        "results/deg/{bioproject}/GO_dotplot.png"
    threads: 8
    shell:
        """
        Rscript workflow/scripts/produce_DEG_with_enrichment.R \
        -p {input.i1} \
        -o results/deg/{wildcards.bioproject}/ \
        -i {input.i2} \
        -v condition \
        -n control \
        -m Homo_sapiens \
        -d org.Hs.eg.db
        """
##        """
##        module load autoload profile/bioinf &&
##        module load autoload r/4.1.0--gcc--10.2.0-python--3.8.6 &&
##        Rscript workflow/scripts/produce_DEG.R \
##        -p {input.i1} \
##        -o results/deg/{wildcards.bioproject}/ \
##        -i {input.i2} \
##        -v condition \
##        -n control \
##        -m Homo_sapiens \
##        -d org.Hs.eg.db
##        """