# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/sample_sheet.csv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
#units: config/units.csv
reference_genome: genome/Homo_sapiens.GRCh38.dna.toplevel.fa
reference_annotation: genome/Homo_sapiens.GRCh38.112.chr.gtf

THREADS:
  zhex: 7
  fqzip: 8
  trimmo: 32
  hisat: 32
  samsort: 16
RESOURCEMOD:
  boost: 80000
  high: 150000
  moretime: "3:00:00"

#ref:
  # Ensembl species name
#  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
#  release: 100
  # Genome build
#  build: GRCh38

#trimming:
#  activate: True

#pca:
#  activate: True
#  labels:
    # columns of sample sheet to use for PCA
#    - condition

#diffexp:
  # contrasts for the deseq2 results method
#  contrasts:
#    A-vs-B:
#      - A
#      - B
#  model: ~condition

#params:
#  trimmomatic:
#    pe:
#      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
#        - "LEADING:3"
#        - "TRAILING:3"
#        - "SLIDINGWINDOW:4:15"
#        - "MINLEN:36"
#    se:
#      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
#        - "LEADING:3"
#        - "TRAILING:3"
#        - "SLIDINGWINDOW:4:15"
#        - "MINLEN:36"
#
