# ---- INPUTS ----
samples: config/sample_sheet.csv

# ---- REFERENCES ----
reference_genome: genome/Homo_sapiens.GRCh38.dna.toplevel.fa
reference_annotation: genome/Homo_sapiens.GRCh38.112.chr.gtf

# ---- RESOURCE TIERS ----
resources:
  tiny:
    threads: 1
    mem_mb: 100
  light:
    threads: 1
    mem_mb: 500
  small:
    threads: 2
    mem_mb: 3000
  medium:
    threads: 4
    mem_mb: 8000
  heavy:
    threads: 8
    mem_mb: 16000
  xheavy:
    threads: 12
    mem_mb: 32000

# ---- Adapter Trimming ----
cutadapt:
  adapter: AGATCGGAAGAGCACACGTCTGAACTCC
  min_length: 18
  max_length: 50
  quality_cutoff: 20
trimmomatic:
  pe:
    - "ILLUMINACLIP:TruSeq3-PE.fa:2:30:10"
    - "LEADING:3"
    - "TRAILING:3"
    - "SLIDINGWINDOW:4:15"
    - "MINLEN:36"
  se:
    - "ILLUMINACLIP:TruSeq3-SE.fa:2:30:10"
    - "LEADING:3"
    - "TRAILING:3"
    - "SLIDINGWINDOW:4:15"
    - "MINLEN:36"

# ---- DESeq2 Analysis ----
deseq2_gene:
  padj: 0.05
  logfc: 0.5

deseq2_transcript:
  padj: 0.05
  logfc: 0.5

deseq2_smallrna:
  padj:
    BEAS_2B_short: 0.02
    HEP_G2_short: 0.02
    default: 0.05
  logfc: 0.2

# ---- Isoform Switch Analysis ----
isoform_switch:
  # --- Pre-filtering thresholds (used before testing) ---
  gene_expression_cutoff: 1.0         # Minimum average gene expression (CPM) to retain the gene
  isoform_expression_cutoff: 1.0      # Minimum average isoform expression (CPM) to retain the isoform
  # --- Post-analysis filtering (after statistical testing) ---
  padj_cutoff: 0.1                    # Maximum adjusted p-value to consider switch significant (liberal for exploration)
  dIF_cutoff: 0.1                     # Minimum absolute change in Isoform Fraction (|dIF|) to count as biologically relevant
  max_genes_to_plot: 30              # Maximum number of significant switching genes to include in the output plot PDF

# ---- GO, KEGG, Reactome Analysis ----
enrichment:
  padj: 0.05
  logfc: 0.5

enrichment_mirna:
  padj: 0.05

# ---- Plotting ----
plotting:
  topn: 30

# ---- Additional resource mods ---
RESOURCEMOD:
  boost: 80000
  high: 150000
  moretime: "3:00:00"
