# ---- INPUTS ----
samples: config/sample_sheet.csv

# ---- REFERENCES ----
reference_genome: genome/Homo_sapiens.GRCh38.dna.toplevel.fa
reference_annotation: genome/Homo_sapiens.GRCh38.112.chr.gtf

# ---- RESOURCE TIERS ----
resources:
  tiny:
    threads: 1
    mem_mb: 100
  light:
    threads: 1
    mem_mb: 500
  small:
    threads: 2
    mem_mb: 3000
  medium:
    threads: 4
    mem_mb: 8000
  heavy:
    threads: 8
    mem_mb: 16000
  xheavy:
    threads: 12
    mem_mb: 32000

# ---- DESeq2 Analysis ----
deseq2:
  padj:
    BEAS_2B_short: 0.02
    HEP_G2_short: 0.02
    default: 0.05
  logfc: 0.2

# ---- Adapter Trimming ----
cutadapt:
  adapter: AGATCGGAAGAGCACACGTCTGAACTCC
  min_length: 18
  max_length: 50
  quality_cutoff: 20

# ---- Plotting ----
plotting:
  topn: 30

# ---- Additional resource mods ---
RESOURCEMOD:
  boost: 80000
  high: 150000
  moretime: "3:00:00"
